debug: false
management.endpoints.web.exposure.include : "*"

logging:
  level:
    com.hyunwoo.project: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: hyunwoo
    password: GUSdn0211!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
#    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always
  # thymleaf.cache: false
#  data.rest:
#    base-path: /api
#    detection-strategy: annotated

---

#spring:
#  config.activa.on-profile: testdb
##  datasource:
##    url: jdbc:mysql://localhost:3306/board;mode=mysql
##    dirverClassName: org.h2.Driver
##  sql.init.mode: always
##  test.databases.replace: none












